//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TripLight.rc
//
#define IDR_MAINFRAME                   101
#define IDR_TRIPLITYPE                  102
#define IDD_ABOUTBOX                    103
#define IDD_MAPPING                     104
#define IDD_OPTIONS                     105
#define IDD_PROGRESS                    106
#define IDD_PROPERTIES                  107
#define IDD_SETTINGS                    108
#define IDS_APP_ABOUT_TEXT              200
#define IDS_APP_LICENSE                 201
#define IDS_IMAGE_SEQ_FOLDER            202
#define IDS_IMAGE_SEQ_OVERWRITE_WARN    203
#define IDS_MIDI_EVENT_TYPE_CHAN_AFT    204
#define IDS_MIDI_EVENT_TYPE_CONTROL     205
#define IDS_MIDI_EVENT_TYPE_KEY_AFT     206
#define IDS_MIDI_EVENT_TYPE_NOTE_OFF    207
#define IDS_MIDI_EVENT_TYPE_NOTE_ON     208
#define IDS_MIDI_EVENT_TYPE_PATCH       209
#define IDS_MIDI_EVENT_TYPE_WHEEL       210
#define IDS_NONE                        211
#define IDP_OLE_INIT_FAILED             212
#define IDC_ABOUT_LICENSE               1001
#define IDC_ABOUT_TEXT                  1002
#define IDC_MAPPING_CHANNEL1            1003
#define IDC_MAPPING_CHANNEL2            1004
#define IDC_MAPPING_CHANNEL3            1005
#define IDC_MAPPING_CHANNEL4            1006
#define IDC_MAPPING_CHANNEL5            1007
#define IDC_MAPPING_CHANNEL6            1008
#define IDC_MAPPING_CHANNEL7            1009
#define IDC_MAPPING_CONTROL1            1010
#define IDC_MAPPING_CONTROL2            1011
#define IDC_MAPPING_CONTROL3            1012
#define IDC_MAPPING_CONTROL4            1013
#define IDC_MAPPING_CONTROL5            1014
#define IDC_MAPPING_CONTROL6            1015
#define IDC_MAPPING_CONTROL7            1016
#define IDC_MAPPING_END1                1017
#define IDC_MAPPING_END2                1018
#define IDC_MAPPING_END3                1019
#define IDC_MAPPING_END4                1020
#define IDC_MAPPING_END5                1021
#define IDC_MAPPING_END6                1022
#define IDC_MAPPING_END7                1023
#define IDC_MAPPING_EVENT1              1024
#define IDC_MAPPING_EVENT2              1025
#define IDC_MAPPING_EVENT3              1026
#define IDC_MAPPING_EVENT4              1027
#define IDC_MAPPING_EVENT5              1028
#define IDC_MAPPING_EVENT6              1029
#define IDC_MAPPING_EVENT7              1030
#define IDC_MAPPING_START1              1031
#define IDC_MAPPING_START2              1032
#define IDC_MAPPING_START3              1033
#define IDC_MAPPING_START4              1034
#define IDC_MAPPING_START5              1035
#define IDC_MAPPING_START6              1036
#define IDC_MAPPING_START7              1037
#define IDC_OPTIONS_MIDI_IN             1038
#define IDC_OPTIONS_MIDI_OUT            1039
#define IDC_OPTIONS_RANDOM_SEED         1040
#define IDC_OPTIONS_SEED_FROM_TIME      1041
#define IDC_OPTIONS_START_FULL_SCREEN   1042
#define IDC_PROGRESS                    1043
#define IDC_PROGRESS_PERCENT            1044
#define IDC_PROPS_COLOR_SPEED           1045
#define IDC_PROPS_COLOR_SPEED_STEP      1046
#define IDC_PROPS_COLOR_VARIANCE        1047
#define IDC_PROPS_COLOR_VARIANCE_STEP   1048
#define IDC_PROPS_COLS                  1049
#define IDC_PROPS_PATTERN               1050
#define IDC_PROPS_ROWS                  1051
#define IDC_SETTINGS_IMAGE_HEIGHT       1052
#define IDC_SETTINGS_IMAGE_HEIGHT_CAP   1053
#define IDC_SETTINGS_IMAGE_SIZE_TYPE    1054
#define IDC_SETTINGS_IMAGE_SIZE_TYPE2   1055
#define IDC_SETTINGS_IMAGE_WIDTH        1056
#define IDC_SETTINGS_IMAGE_WIDTH_CAP    1057
#define IDC_SETTINGS_RECORD_SECONDS     1058
#define ID_FILE_EXPORT                  32771
#define ID_FILE_RECORD                  32772
#define ID_IMAGE_COLOR_JUMP             32773
#define ID_IMAGE_COLS_LESS              32774
#define ID_IMAGE_COLS_MORE              32775
#define ID_IMAGE_PATTERN1               32776
#define ID_IMAGE_PATTERN2               32777
#define ID_IMAGE_PATTERN3               32778
#define ID_IMAGE_PATTERN4               32779
#define ID_IMAGE_PATTERN5               32780
#define ID_IMAGE_PATTERN6               32781
#define ID_IMAGE_PATTERN7               32782
#define ID_IMAGE_PATTERN8               32783
#define ID_IMAGE_ROWS_LESS              32784
#define ID_IMAGE_ROWS_MORE              32785
#define ID_IMAGE_SPEED_FASTER           32786
#define ID_IMAGE_SPEED_SLOWER           32787
#define ID_IMAGE_VARIANCE_LESS          32788
#define ID_IMAGE_VARIANCE_MORE          32789
#define ID_INDICATOR_BACKWARD           32790
#define ID_INDICATOR_COLOR_SPEED        32791
#define ID_INDICATOR_COLOR_SPEED_VAR    32792
#define ID_INDICATOR_COLS               32793
#define ID_INDICATOR_PAUSE              32794
#define ID_INDICATOR_ROWS               32795
#define ID_TOOLS_FADE                   32796
#define ID_TOOLS_MAPPING                32797
#define ID_TOOLS_OPTIONS                32798
#define ID_TOOLS_PROPERTIES             32799
#define ID_TOOLS_SETTINGS               32800
#define ID_VIEW_BACKWARD                32801
#define ID_VIEW_PAUSE                   32802
#define ID_VIEW_PIANO                   32803
#define ID_VIEW_SHOW_MESH               32804
#define ID_VIEW_SINGLE_STEP             32805
#define ID_WINDOW_ESCAPE                32806
#define ID_WINDOW_FULL_SCREEN           32807

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
